#!/bin/sh
# labwc autostart - Windows 95/98 Style
# Path: ~/.config/labwc/autostart

# Set keyboard layout to Spanish Latin America
setxkbmap latam

# Set wallpaper to teal (Windows 95 default)
swaybg -c 008080 &

# Start waybar with Windows 95 style
waybar &

# Notification daemon (optional)
# mako &

# Network manager applet (if available)
# nm-applet --indicator &

# Audio control (if using PipeWire/PulseAudio)
# pavucontrol &