#!/usr/bin/env bash
# Por defecto usar 16384M como tamaño máximo de bloque zram.
MAX_SIZE=16384
# Cantidad de memoria a usar para zram, entre 1 y 200.
PORTION=100
# Por defecto, comprimir con zstd, que tiene una relación de compresión promedio de 3.37.
ALGO=zstd
# Valores más altos incentivan al kernel a mover páginas a swap con mayor prontitud.
SWAPPINESS=180
# Por defecto usar 16384M como tamaño máximo de bloque zram.
MAX_SIZE=16384
# Cantidad de memoria a usar para zram, entre 1 y 200.
PORTION=100
# Por defecto, comprimir con zstd, que tiene una relación de compresión promedio de 3.37.
ALGO=zstd
# Valores más altos incentivan al kernel a mover páginas a swap con mayor prontitud.
SWAPPINESS=180