#!/usr/bin/env bash
# Por defecto usar 16384M como tamaño máximo de bloque zram.
export MAX_SIZE=16384

# Cantidad de memoria a usar para zram, entre 1 y 200.
export PORTION=100

# Por defecto, comprimir con zstd, que tiene una relación de compresión promedio de 3.37.
export ALGO=zstd

# Valores más altos incentivan al kernel a mover páginas a swap con mayor prontitud.
export SWAPPINESS=180
